---
http_interactions:
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - <%= vcr_test_tenant %>
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Connection:
      - keep-alive
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '150'
      Date:
      - Tue, 24 Oct 2017 07:43:43 GMT
    body:
      encoding: UTF-8
      string: '{"MetricsService":"STARTED","Implementation-Version":"0.26.1.Final","Built-From-Git-SHA1":"45b148c834ed62018f153c23187b4436ae4208fe","Cassandra":"up"}'
    http_version: 
  recorded_at: Tue, 24 Oct 2017 07:43:43 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/metrics/availability/<%= id %>/raw
    body:
      encoding: UTF-8
      string: '[{"timestamp":<%= minus50 %>,"value":"up"},{"timestamp":<%= minus40 %>,"value":"up"},{"timestamp":<%= minus30 %>,"value":"down"},{"timestamp":<%= minus20 %>,"value":"down"},{"timestamp":<%= minus10 %>,"value":"down"},{"timestamp":<%= now %>,"value":"up"}]'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - <%= vcr_test_tenant %>
      Content-Type:
      - application/json
      Content-Length:
      - '253'
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Connection:
      - keep-alive
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Content-Length:
      - '0'
      Date:
      - Tue, 24 Oct 2017 07:43:43 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Tue, 24 Oct 2017 07:43:43 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/metrics/availability/<%= id %>/raw/?distinct=true&order=ASC
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - <%= vcr_test_tenant %>
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Tue, 24 Oct 2017 07:43:43 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '126'
    body:
      encoding: UTF-8
      string: '[{"timestamp":<%= minus50 %>,"value":"up"},{"timestamp":<%= minus30 %>,"value":"down"},{"timestamp":<%= now %>,"value":"up"}]'
    http_version: 
  recorded_at: Tue, 24 Oct 2017 07:43:43 GMT
recorded_with: VCR 3.0.3
