---
http_interactions:
- request:
    method: get
    uri: http://<%= super_secret_username %>:<%= super_secret_password %>@localhost:8080/hawkular/inventory/entity/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fsubsystem=datasources%2Fdata-source=ExampleDS/d;configuration
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Host:
      - localhost:8080
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 10 Aug 2016 22:35:37 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '585'
    body:
      encoding: UTF-8
      string: |-
        {
          "path" : "/t;hawkular/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fsubsystem%3Ddatasources%2Fdata-source%3DExampleDS/d;configuration",
          "properties" : {
            "__identityHash" : "db85f6b08996789d6b315151197ef115897dc12"
          },
          "name" : "configuration",
          "identityHash" : "db85f6b08996789d6b315151197ef115897dc12",
          "value" : {
            "Username" : "sa",
            "Driver Name" : "h2",
            "JNDI Name" : "java:jboss/datasources/ExampleDS",
            "Connection URL" : "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE",
            "Enabled" : "true",
            "Password" : "sa"
          }
        }
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:37 GMT
recorded_with: VCR 3.0.3
